version: "3.8"
services:
  deskbird-auto:
    image: amaghast/deskbird-auto:latest
    container_name: deskbird-auto
    ports:
      - "2713:2713"
    environment:
      - DESKBIRD_EMAIL=${DESKBIRD_EMAIL}
      - DESKBIRD_PASSWORD=${DESKBIRD_PASSWORD}
      - DESKBIRD_APP_KEY=${DESKBIRD_APP_KEY}
      - TZ=Europe/Paris
    restart: unless-stopped
